services:

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"                   
    # volumes:                       # При разработке production!
    #   - ./frontend:/app            # только для разработки (но тогда лучше vite dev server)
    restart: unless-stopped
    networks:
      - app-network
