services:
  frontend:
    container_name: 
      frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - DMS=localhost:${DATA_MANIPULATION_SERVICE_PORT}
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    networks:
      - network
    depends_on:
      - data_manipulation_service
    
  
  data_manipulation_service:
    container_name: 
      data_manipulation_service
    build: 
      context: ./data_manipulation_service
      dockerfile: Dockerfile
    volumes:
      - ./datasets_storage:/app/datasets
    ports:
      - "${DATA_MANIPULATION_SERVICE_PORT}:${DATA_MANIPULATION_SERVICE_PORT}"
    networks:
      - network
  
  # experiment_orchestrator:
    # Todo

  tasker_service:
    container_name: 
      tasker_service
    build: 
      context: ./tasker_service
      dockerfile: Dockerfile
    ports:
      - "${TASKER_PORT}:${TASKER_PORT}"
    networks:
      - network

    
  trainer_service:
    container_name: 
      trainer_service
    build: 
      context: ./trainer_service
      dockerfile: Dockerfile
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - ./datasets_storage:/app/datasets
    ports:
      - "${TRAINER_SERVICE_PORT}:${TRAINER_SERVICE_PORT}"
    environment:
      - TASKER_DOMAIN=tasker_service:${TASKER_PORT}
      - METRICS_DOMAIN=metrics_service:${METRICS_SERVICE_PORT}
    depends_on:
      - metrics_service
      - tasker_service
    networks:
      - network
    shm_size: 2gb

  metrics_service:
    container_name: 
      metrics_service
    build:
      context: ./metrics_service
      dockerfile: Dockerfile
    ports: 
      - "${METRICS_SERVICE_PORT}:${METRICS_SERVICE_PORT}"
    networks:
      - network

  # agent_monitoring:
    # Todo

  agent_office:
    container_name: 
      agent_office
    build: 
      context: ./agent_office
      dockerfile: Dockerfile
    ports:
      - "${AGENT_OFFICE_PORT}:${AGENT_OFFICE_PORT}"
    environment:
      - DMS_DOMEN=data_manipulation_service:${DATA_MANIPULATION_SERVICE_PORT}
      - TASKER_DOMEN=tasker_service:${TASKER_PORT}
      - TRAINER_DOMEN=trainer_service:${TRAINER_SERVICE_PORT}
    networks:
      - network
  

  # deployment_service:
    # Todo

networks:
  network:
    driver: bridge
    name: network
