
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - VITE_API_URL=http://dms:8000
    networks:
      - app-network

  dms:
    build:
      context: ./data_manipulation_service
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=production
    volumes:
      - /datasets_storage:/app/datasets
    networks:
      - app-network

networks:
  app-network:
    driver: bridge