blank_issues_enabled: false
contact_links:
  - name: "💬 Есть вопрос или предложение?"
    url: https://github.com/kisinwi-dev/kisinwi-plt/discussions
    about: "Пожалуйста, используйте Discussions для общих вопросов и обсуждений, не оформляя issue."